---
- hosts: [servers]
  become: true
  tasks:
  - name: "Устанавливаем apt-transport-https"
    ansible.builtin.apt:
      name: "apt-transport-https"
      state: "latest"
      update_cache: true
  - name: "Добавляем ключ репо Elastic"
    shell: sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add 
  - name: "Добавляем пакеты в систему"
    shell: sudo echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
  - name: "Устанавливаем Elastic"
    ansible.builtin.apt:
      name: "elasticsearch"
      state: "latest"
      update_cache: true
  - name: "Устанавливаем Kibana"
    ansible.builtin.apt:
      name: "kibana"
      state: "latest"
      update_cache: true
  - name: "Устанавливаем Logstash"
    ansible.builtin.apt:
      name: "logstash"
      state: "latest"
      update_cache: true
  - name: "Устанавливаем Nginx"
    ansible.builtin.apt:
      name: "nginx"
      state: "latest"
      update_cache: true
